//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microwork_Platform_for_the_unemployed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Id { get; set; }
        public string posted_by { get; set; }
        public System.DateTime created_date { get; set; }
        public string job_description { get; set; }
        public string job_location { get; set; }
        public bool is_active { get; set; }
    }
}
