//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microwork_Platform_for_the_unemployed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public byte[] Resume { get; set; }
        public string MobileNumber { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Experience { get; set; }
        public string KeySkills { get; set; }
        public string Higher { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string DesiredProvince { get; set; }
        public string DesiredCity { get; set; }
        public bool IsEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
        public string Password { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string ResetPasswordCode { get; set; }
    }
}
